check50:
  files: &check50_files
    - !exclude "*"
    - !exclude find.c
    - !exclude helpers.h
    - !exclude sort.c
    - !exclude generate.c
    - !require helpers.c
    - !require Makefile
submit50:
  files: *check50_files
